# =============================================================================
# PARAMETERS.YML - ACTUALIZADO PARA EP2
# Proyecto: Predicción y Preparación de Pandemias
# =============================================================================

# =============================================================================
# BUSINESS UNDERSTANDING PARAMETERS
# =============================================================================

project:
  name: "Predicción y Preparación de Pandemias"
  objective: "Evaluar preparación de países ante pandemias usando ML"
  target_classification: "preparedness_level" # Alto, Medio, Bajo
  target_regression: "healthcare_capacity_score" # Score continuo

# =============================================================================
# DATA QUALITY PARAMETERS
# =============================================================================

data_quality:
  missing_threshold: 0.7 # 70% missing values máximo por columna
  outlier_method: "IQR"
  outlier_threshold: 3.0 # Factor IQR
  min_records_per_country: 30

# =============================================================================
# DATA CLEANING PARAMETERS
# =============================================================================

cleaning:
  date_columns:
    - "date"
    - "vaccination_date"

  numeric_imputation:
    strategy: "median" # median, mean, forward_fill

  categorical_imputation:
    strategy: "mode"

  epidemiological_vars:
    imputation: "forward_fill" # Para variables epidemiológicas

  socioeconomic_vars:
    imputation: "median" # Para variables socioeconómicas

# =============================================================================
# FEATURE ENGINEERING PARAMETERS
# =============================================================================

feature_engineering:
  rolling_windows:
    - 7 # Semana
    - 14 # 2 semanas
    - 30 # Mes

  aggregation_functions:
    - "mean"
    - "sum"
    - "max"
    - "std"

  lag_features:
    - 7
    - 14
    - 30

  encoding:
    categorical_method: "onehot" # onehot, label, target
    handle_unknown: "ignore"

# =============================================================================
# TARGET DEFINITIONS
# =============================================================================

targets:
  classification:
    target_name: "preparedness_level"
    thresholds:
      high: 0.7
      medium: 0.4
    features_for_calculation:
      - "vaccination_rate"
      - "cases_per_million"
      - "deaths_per_million"
      - "hospital_capacity"

  regression:
    target_name: "healthcare_capacity_score"
    min_value: 0
    max_value: 100
    features_for_calculation:
      - "icu_beds_per_100k"
      - "hospital_beds_per_100k"
      - "doctors_per_1000"
      - "nurses_per_1000"

# =============================================================================
# EP2: MODEL TRAINING PARAMETERS
# =============================================================================

model_training:
  test_size: 0.2
  random_state: 42
  n_jobs: -1 # Usar todos los cores disponibles
  verbose: 1

# =============================================================================
# EP2: CLASSIFICATION MODELS PARAMETERS (OPTIMIZED)
# =============================================================================

classification_models:
  # ---------------------------------------------------------------------------
  # LOGISTIC REGRESSION (OPTIMIZADO)
  # ---------------------------------------------------------------------------
  logistic_regression:
    param_grid:
      C: [0.1, 1]
      penalty: ["l2"]
      solver: ["lbfgs"]
      max_iter: [2000]
    cv: 3
    scoring: "f1_weighted"
    n_jobs: -1

  # ---------------------------------------------------------------------------
  # RANDOM FOREST CLASSIFIER (OPTIMIZADO)
  # ---------------------------------------------------------------------------
  random_forest_classifier:
    param_grid:
      n_estimators: [100]
      max_depth: [20]
      min_samples_split: [2]
      min_samples_leaf: [1]
      max_features: ["sqrt"]
    cv: 3
    scoring: "f1_weighted"
    n_jobs: -1

  # ---------------------------------------------------------------------------
  # XGBOOST CLASSIFIER (OPTIMIZADO)
  # ---------------------------------------------------------------------------
  xgboost_classifier:
    param_grid:
      n_estimators: [100]
      max_depth: [5]
      learning_rate: [0.1]
      subsample: [0.8]
      colsample_bytree: [0.8]
    cv: 3
    scoring: "f1_weighted"
    n_jobs: -1

  # ---------------------------------------------------------------------------
  # SVM CLASSIFIER (OPTIMIZADO)
  # ---------------------------------------------------------------------------
  svm_classifier:
    param_grid:
      C: [1]
      kernel: ["rbf"]
      gamma: ["scale"]
    cv: 3
    scoring: "f1_weighted"
    n_jobs: -1
    random_state: 42

  # ---------------------------------------------------------------------------
  # GRADIENT BOOSTING CLASSIFIER (OPTIMIZADO)
  # ---------------------------------------------------------------------------
  gradient_boosting_classifier:
    param_grid:
      n_estimators: [100]
      max_depth: [5]
      learning_rate: [0.1]
      subsample: [0.8]
      min_samples_split: [2]
    cv: 3
    scoring: "f1_weighted"
    n_jobs: -1

# =============================================================================
# EP2: REGRESSION MODELS PARAMETERS (OPTIMIZED - MINIMAL)
# =============================================================================

regression_models:
  # ---------------------------------------------------------------------------
  # LINEAR REGRESSION (OPTIMIZED)
  # ---------------------------------------------------------------------------
  linear_regression:
    param_grid:
      fit_intercept: [True] # Solo 1 valor
    cv: 3 # Reducido de 5 a 3
    scoring: "r2"
    n_jobs: -1

  # ---------------------------------------------------------------------------
  # RIDGE REGRESSION (OPTIMIZED)
  # ---------------------------------------------------------------------------
  ridge_regression:
    param_grid:
      alpha: [1.0] # Solo 1 valor (en lugar de [0.1, 1, 10])
      fit_intercept: [True] # Solo 1 valor
    cv: 3
    scoring: "r2"
    n_jobs: -1

  # ---------------------------------------------------------------------------
  # RANDOM FOREST REGRESSOR (OPTIMIZED)
  # ---------------------------------------------------------------------------
  random_forest_regressor:
    param_grid:
      n_estimators: [100] # Solo 1 valor
      max_depth: [20] # Solo 1 valor
      min_samples_split: [2] # Solo 1 valor
      min_samples_leaf: [1] # Solo 1 valor
      max_features: ["sqrt"] # Solo 1 valor
    cv: 3
    scoring: "r2"
    n_jobs: -1

  # ---------------------------------------------------------------------------
  # XGBOOST REGRESSOR (OPTIMIZED)
  # ---------------------------------------------------------------------------
  xgboost_regressor:
    param_grid:
      n_estimators: [100] # Solo 1 valor
      max_depth: [5] # Solo 1 valor
      learning_rate: [0.1] # Solo 1 valor
      subsample: [0.8] # Solo 1 valor
      colsample_bytree: [0.8] # Solo 1 valor
    cv: 3
    scoring: "r2"
    n_jobs: -1

  # ---------------------------------------------------------------------------
  # GRADIENT BOOSTING REGRESSOR (OPTIMIZED)
  # ---------------------------------------------------------------------------
  gradient_boosting_regressor:
    param_grid:
      n_estimators: [100] # Solo 1 valor
      max_depth: [5] # Solo 1 valor
      learning_rate: [0.1] # Solo 1 valor
      subsample: [0.8] # Solo 1 valor
      min_samples_split: [2] # Solo 1 valor
    cv: 3
    scoring: "r2"
    n_jobs: -1

# =============================================================================
# EP2: EVALUATION PARAMETERS
# =============================================================================

evaluation:
  classification_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "roc_auc"

  regression_metrics:
    - "r2"
    - "mae"
    - "mse"
    - "rmse"
    - "mape"

  cross_validation:
    cv: 5
    shuffle: True
    stratify: True # Para clasificación

  feature_importance:
    top_n: 20 # Top N features más importantes

# =============================================================================
# EP3: UNSUPERVISED LEARNING PARAMETERS (Para futuro)
# =============================================================================

unsupervised_learning:
  clustering:
    kmeans:
      n_clusters_range: [2, 3, 4, 5, 6]
      random_state: 42

    dbscan:
      eps_range: [0.3, 0.5, 0.7]
      min_samples: [5, 10, 15]

  dimensionality_reduction:
    pca:
      n_components: 0.95 # Explicar 95% de varianza

    tsne:
      n_components: 2
      perplexity: [30, 50]
      random_state: 42
